---
ourcompose_nextcloud_state: 'running'
ourcompose_dep_state: "{{ ourcompose_nextcloud_state }}"
# https://nextcloud.com/changelog/
ourcompose_nextcloud_version: '25'
ourcompose_nextcloud_storage: 'local'
ourcompose_nextcloud_backend_password: 'testpassword'
ourcompose_nextcloud_admin_user: 'admin'
ourcompose_nextcloud_admin_password: 'testpassword'
ourcompose_nextcloud_legacy_dbtableprefix: False
ourcompose_nextcloud_bind_mountpoints:
  - {location: '/nextcloud/core/', directory: '/usr/src/nextcloud/core'}
  - {location: '/nextcloud/apps/', directory: '/usr/src/nextcloud/apps'}
ourcompose_nextcloud_mariadb_present: |
  CREATE USER IF NOT EXISTS 'nextcloud'@'%' IDENTIFIED BY '{{ ourcompose_nextcloud_backend_password }}';
  FLUSH privileges;
  CREATE DATABASE IF NOT EXISTS nextcloud;
  GRANT ALL PRIVILEGES ON nextcloud.* TO 'nextcloud'@'%' IDENTIFIED BY '{{ ourcompose_nextcloud_backend_password }}';
  FLUSH privileges;
ourcompose_nextcloud_mariadb_absent: |
  DROP USER IF EXISTS 'nextcloud'@'%';
  DROP DATABASE IF EXISTS nextcloud;
ourcompose_nextcloud_healthcheck: |
  curl -sSL --fail localhost/status.php \
  || exit 1
