---
ourcompose_wordpress_state: present
ourcompose_wordpress_version: '5.7'
ourcompose_wordpress_storage: 'local'
ourcompose_wordpress_title: 'Wordpress Blog'
ourcompose_wordpress_admin_password: 'testpassword'
ourcompose_wordpress_backend_password: 'testpassword'
ourcompose_wordpress_mariadb_present: |
  CREATE USER IF NOT EXISTS 'wordpress'@'%' IDENTIFIED BY '{{ ourcompose_wordpress_backend_password }}';
  CREATE DATABASE IF NOT EXISTS wordpress;
  GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'@'%';
ourcompose_wordpress_mariadb_absent: |
  DROP USER IF EXISTS 'wordpress'@'%';
  DROP DATABASE IF EXISTS wordpress;
ourcompose_wordpress_healthcheck: |
  curl -sSL --fail --insecure nginx/wordpress \
  || exit 1
