# #
# # TODO: Figure out how I want to control the hosts.inv file from the playbooks or the pipeline
# #
# setup:
#   image: 'ubuntu:18.04'
#   stage: deploy
#   script_script:
#     - apt-get install -y ansible
#     - ansible-galaxy install -fr ./requirements.yml
#     - git clone $ENVIRONMENT_REPO ./environment
#     - ansible-playbook -i environment/hosts.inv playbooks/all_env_services.yml
# 
# deploy:
#   image: 'ubuntu:18.04'
#   stage: deploy
#   script_script:
#     - apt-get install -y ansible
#     - ansible-galaxy install -fr ./requirements.yml
#     - git clone $ENVIRONMENT_REPO ./environment
#     - ansible-playbook -i environment/hosts.inv playbooks/deploy_new_environment_domain_droplet.yml
#     - ansible-playbook -i environment/hosts.inv playbooks/all_env_services.yml
# 
# migrate:
#   image: 'ubuntu:18.04'
#   stage: deploy
#   script_script:
#     - apt-get install -y ansible
#     - ansible-galaxy install -fr ./requirements.yml
#     - git clone $ENVIRONMENT_REPO ./environment
#     - ansible-playbook -i environment/hosts.inv playbooks/deploy_new_environment_domain_droplet.yml
#     - ansible-playbook -i environment/hosts.inv playbooks/all_env_services.yml
#     - ansible-playbook -i environment/hosts.inv playbooks/transfer_data.yml
#     - ansible-playbook -i environment/hosts.inv playbooks/delete_oldest_environment_domain_droplet_and_block_storage.yml
