---
- src: nickjj.docker
  version: 'v1.8.0'
  name: docker
- src: git@gitlab.com:smacz/role-compositional
  scm: git
  version: andrewcz-ourcompose-515
  name: compositional
- src: geerlingguy.certbot
  name: certbot
