---
- src: nickjj.docker
  version: 'v1.8.0'
  name: docker
- src: git@gitlab.com:smacz/role-compositional
  scm: git
  version: stable-1.3
  name: compositional
- src: geerlingguy.certbot
  name: certbot
