---
- src: nickjj.docker
  version: 'v1.8.0'
  name: docker
- src: https://gitlab.com/smacz/play-compositional.git
  scm: git
  version: tags/v2.2.0
  name: compositional
- src: geerlingguy.certbot
  name: certbot
- src: oefenweb.swapfile
  name: swapfile
