---
- src: nickjj.docker
  version: 'v1.8.0'
  name: docker
- src: git@gitlab.com:compositionalenterprises/role-compositional
  scm: git
  version: v2.2.1
  name: compositional
- src: geerlingguy.certbot
  name: certbot
- src: oefenweb.swapfile
  name: swapfile
