---
- src: nickjj.docker
  name: docker
- src: git@gitlab.com:compositionalenterprises/role-compositional
  scm: git
  version: stable-2.5
  name: compositional
- src: geerlingguy.certbot
  name: certbot
- src: oefenweb.swapfile
  name: swapfile
