---
dependencies:
  # We do a couple of things here. First, this is explicit, rather than
  # implicit. Hence, we don't rely on other role's imports to determine which
  # get pulled in for any given run.
  - compositionalenterprises.ourcompose.common
  - role: compositionalenterprises.ourcompose.nginx
    # nginx and portal are only when "running", to the exclusion of
    # "absent" and "stopped".
    when: ourcompose_dep_state == 'running'
  - role: compositionalenterprises.ourcompose.mariadb
    ourcompose_mariadb_restarted: false
    # This means that "absent" will pull in mariadb variables that is
    # needed to purge the databaase, without having to re-run portal
    # or nginx
    when: ourcompose_dep_state != 'stopped'
  - role: compositionalenterprises.ourcompose.portal
    ourcompose_portal_restarted: false
    when: ourcompose_dep_state == 'running'
