---
- name: (mariadb) The latest mariadb service is build and present
  docker_service:
    project_name: mariadb
    definition:
      version: '3.6'
      services:
          mariadb:
              image: mariadb
              container_name: mariadb
              restart: always
              volumes:
                  - mysql:/var/lib/mysql
                  - conf.d:/etc/mysql/conf.d
              networks:
                  - backend
              environment:
                  MYSQL_ROOT_PASSWORD: "{{ compositional_mysql_root_password }}"
      volumes:
          mysql:
          conf.d:
      networks:
          backend:
              name: backend
    build: "{{ compositional_backend_build }}"
    state: "present"
  register: backend_output

- name: (mariadb) Set Backend Type
  set_fact:
    compositional_backend_type: 'mysql'
