---
- name: (nextcloud) Nginx conf is deployed
  template:
    src: "nginx_nextcloud.conf.j2"
    dest: "/var/lib/docker/volumes/nginx_conf.d/_data/{{ environment_domain }}/nextcloud.conf"
  notify: 'Restart Frontend'

- block:

  - name: (nextcloud) The database service is up and initialized
    # We're running a while loop to check to ensure that the mysql database has
    # initialized:
    #   https://stackoverflow.com/questions/25503412/how-do-i-know-when-my-docker-mysql-container-is-up-and-mysql-is-ready-for-taking
    shell: 'docker exec -i {{ backend_output.ansible_facts.keys()[0] }} bash -c "while mysql -uroot -p{{ compositional_mysql_root_password }} -e \"SHOW DATABASES;\" 2>&1 | grep -e \"ERROR 2002\|ERROR 1045\"; do sleep 1; done; echo \"SHOW DATABASES SUCCEEDED!!!\""'

  - name: (nextcloud) Set up the database
    # We have to use `.keys()[0]` to get the name of the container. If we
    # wanted to, we should probably walk down the data structure to get the
    # actual name, but since for the time being we name the name of the service
    # the same as the container, it's not really going to affect us now, as
    # long as we stick to that paradigm.
    shell: docker exec -i {{ backend_output.ansible_facts.keys()[0] }} mysql -uroot -p{{ compositional_mysql_root_password }} <<< "{{ compositional_nextcloud_mysql_script }}"
    args:
      executable: '/bin/bash'

  - name: (nextcloud) The MYSQL latest nextcloud service is built and {{ compositional_nextcloud_state }}
    docker_service:
      project_name: nextcloud
      definition:
        version: '3.6'
        services:
            nextcloud:
                image: nextcloud
                container_name: nextcloud
                volumes:
                    - data:/var/www/html/data
                    - config:/var/www/html/config
                    - themes:/var/www/html/themes
                networks:
                    - frontend
                    - backend
                environment:
                    MYSQL_HOST: "{{ backend_output.ansible_facts.keys()[0] }}"
                    MYSQL_DATABASE: "nextcloud"
                    MYSQL_USER: "nextcloud"
                    MYSQL_PASSWORD: "{{ compositional_nextcloud_backend_password }}"
                    NEXTCLOUD_ADMIN_USER: "{{ compositional_nextcloud_admin_user }}"
                    NEXTCLOUD_ADMIN_PASSWORD: "{{ compositional_nextcloud_admin_password }}"
        volumes:
            data:
            config:
            themes:
        networks:
            frontend:
                external: true
            backend:
                external: true
      build: "{{ compositional_nextcloud_build }}"
      state: "{{ compositional_nextcloud_state }}"
    register: compositional_nextcloud_output

  when: compositional_backend_type == 'mysql'

- block:

  - name: (nextcloud) The POSTGRES latest nextcloud service is built and {{ compositional_nextcloud_state }}
    docker_service:
      project_name: nextcloud
      definition:
        version: '3.6'
        services:
            nextcloud:
                image: nextcloud
                container_name: nextcloud
                volumes:
                    - data:/var/www/html/data
                    - config:/var/www/html/config
                    - themes:/var/www/html/themes
                networks:
                    - frontend
                    - backend
                environment:
                    POSTGRES_DB: "nextcloud"
                    POSTGRES_USER: "nextcloud"
                    POSTGRES_PASSWORD: "{{ compositional_nextcloud_backend_password }}"
                    POSTGRES_HOST: "{{ backend_output.ansible_facts.keys()[0] }}"
                    NEXTCLOUD_ADMIN_USER: "{{ compositional_nextcloud_admin_user }}"
                    NEXTCLOUD_ADMIN_PASSWORD: "{{ compositional_nextcloud_admin_password }}"
        volumes:
            data:
            config:
            themes:
        networks:
            frontend:
                external: true
            backend:
                external: true
      build: "{{ compositional_nextcloud_build }}"
      state: "{{ compositional_nextcloud_state }}"
    register: compositional_nextcloud_output
    when: compositional_backend_type == 'postgres'

  when: compositional_backend_type == 'mysql'

- name: (nextcloud) config.php is configured with trusted_domains
  lineinfile:
    path: '/var/lib/docker/volumes/nextcloud_config/_data/config.php'
    insertafter: "0 => 'localhost'"
    line: "    {{ loop_idx + 1 }} => {{ loop_item }},"
  loop:
    - "{{ environment_domain }}"
    - "nextcloud"
  loop_control:
    loop_var: loop_item
    index_var: loop_idx

- name: (nextcloud) config.php is configured with overwritewebroot
  lineinfile:
    path: '/var/lib/docker/volumes/nextcloud_config/_data/config.php'
    insertafter: "overwrite.cli.url"
    line: "  'overwritewebroot' => '/nextcloud',"
