---
- name: (nginx) The latest nginx service is built and present
  docker_service:
    project_name: nginx
    definition:
      version: '3.6'
      services:
          nginx:
              image: 'nginx:stable'
              container_name: nginx
              restart: always
              ports:
                  - "80:80"
                  - "443:443"
              volumes:
                  - conf.d:/etc/nginx/conf.d
                  - html:/usr/share/nginx/html
                  - /etc/letsencrypt:/etc/letsencrypt
              networks:
                  - frontend
      volumes:
          conf.d:
          html:
      networks:
          frontend:
              name: frontend
    build: "{{ compositional_frontend_build }}"
    state: "{{ compositional_frontend_state }}"
  register: frontend_output

- name: (nginx) Nginx default.conf is deployed
  template:
    src: nginx_default.conf.j2
    dest: '/var/lib/docker/volumes/nginx_conf.d/_data/default.conf'
  notify: 'Restart Frontend'

- name: (nginx) Nginx index.html is deployed
  template:
    src: nginx_index.html.j2
    dest: '/var/lib/docker/volumes/nginx_html/_data/index.html'
  notify: 'Restart Frontend'

- name: (nginx) Services directory is created
  file:
    path: "/var/lib/docker/volumes/nginx_conf.d/_data/{{ environment_domain }}"
    state: directory

- name: (nginx) Set Frontend Type
  set_fact:
    compositional_frontend_type: 'nginx'
