---
- name: (wordpress) Nginx conf is deployed
  template:
    src: "nginx_wordpress.conf.j2"
    dest: "/var/lib/docker/volumes/nginx_conf.d/_data/{{ environment_domain }}/wordpress.conf"
  notify: 'Restart Frontend'

- name: (wordpress) The MySQL database service is up and initialized
  # We're running a while loop to check to ensure that the mysql database has
  # initialized:
  #   https://stackoverflow.com/questions/25503412/how-do-i-know-when-my-docker-mysql-container-is-up-and-mysql-is-ready-for-taking
  shell: 'docker exec -i {{ compositional_backend_output.ansible_facts.keys() | list | first }} bash -c "while mysql -uroot -p{{ compositional_mysql_root_password }} -e \"SHOW DATABASES;\" 2>&1 | grep -e \"ERROR 2002\|ERROR 1045\"; do sleep 1; done; echo \"SHOW DATABASES SUCCEEDED!!!\""'

- name: (wordpress) Set up the MySQL database
  # We have to use `.keys() | list | first` to get the name of the container. If we
  # wanted to, we should probably walk down the data structure to get the
  # actual name, but since for the time being we name the name of the service
  # the same as the container, it's not really going to affect us now, as
  # long as we stick to that paradigm.
  shell: docker exec -i {{ compositional_backend_output.ansible_facts.keys() | list | first }} mysql -uroot -p{{ compositional_mysql_root_password }} <<< "{{ compositional_wordpress_mysql_script }}"
  args:
    executable: '/bin/bash'

- name: (wordpress) The latest wordpress service is built and {{ compositional_wordpress_state }}
  docker_service:
    project_name: wordpress
    definition:
      version: '3.6'
      services:
          wordpress:
              image: wordpress
              container_name: wordpress
              volumes:
                  - themes:/var/www/html/wp-content/themes
                  - plugins:/var/www/html/wp-content/plugins
              networks:
                  - frontend
                  - backend
              environment:
                WORDPRESS_DB_HOST: "{{ compositional_backend_output.ansible_facts.keys() | list | first }}"
                WORDPRESS_DB_USER: 'wordpress'
                WORDPRESS_DB_PASSWORD: "{{ compositional_wordpress_backend_password }}"
                WORDPRESS_DB_NAME: "wordpress"
                WORDPRESS_CONFIG_EXTRA: |
                  /* Fix Subdirectory config */
                  define('WP_SITEURL', 'https://{{ environment_domain }}/blog');
                  define('WP_HOME', 'https://{{ environment_domain }}/blog');

      volumes:
          themes:
          plugins:
      networks:
          frontend:
              external: true
          backend:
              external: true
    build: "{{ compositional_wordpress_build }}"
    state: "{{ compositional_wordpress_state }}"
  register: compositional_wordpress_output
