---
ourcompose_portal_state: 'running'
ourcompose_dep_state: "{{ ourcompose_portal_state }}"
ourcompose_portal_version: 'stable-4'
ourcompose_portal_storage: 'local'
ourcompose_portal_restarted: 'yes'
ourcompose_portal_role_branch: 'master'
ourcompose_portal_backend_password: 'testpassword'
ourcompose_portal_production_key: 'cb569b8ea39a7dada216dffaee8f7ec3'
ourcompose_portal_production_yml_enc: '2gafMr5rpo3vdDVWfY14BYXbvwtQLlK8o14v6pW0451Eos1M+Jl60lKPT8LIzLWHHZT7NlEZOMmfYAoI51usrhG+JIHMToGBaAYE6SA3c10f9JIzoWxowbWSgS3Kj3DOP+7xdJxAhKXQd7q50Mt67B9uTtMw2HJb1q2zefxPsQ2o9tORs4Sxf6OBNLdTOdw0mjNYbHao0k16gbnMf5fLuBIeQWuSDmtAt6RtIIUYhjXPNp8jLVOwTZgoQxQJRhD8c2OexNJEi8/m6vts6KOzlrkjfVNzLG92tNhCZUtf7NJezFpBSOT/b1v7B1yq325j+zIfOdy6x5qlp0rM026nDzjqJ63tFKk76+BkG8LFa0dQFKRc45IoCmzUnpyDSHnmMyNIcYV87OYHQPwRjgaOUP35V88/CwuiVEkaRN2D/M4HY7GrWY56xy/xmtRov776MsB3kwvsZYMo+YwX/ZUQIBI/X1f+a85n9imAuytnnlqmMHiM7MtfNReN6GVpBnBmjvoSZaKyj5wp0qD5UkRkM9AiSlx7+uOx4jdcfjYt8oSexOlt58PzmCGYRMQlz7DSSni4bbFAIxnd0eDpw2CpQB9+Qve9dT0XEjR/SQAcyPBijIET15D7O4iCsfZ3/Qv9fBkUBvCTGbRAQ62nF62mneP4qFpXEU0UOIzlnvUb6T+LHrYd9QMycWFFzldo00JCO+L6wxhfJgwC3/h0/eHw3RZpgNvrUITyuJQ9p3VG0Dw5qXez--+F1Z9zuM4G3yDZWg--oZOTb5Qt2S5KFZ8Wm8KaFA=='
ourcompose_portal_ourcomposebot_ro_key: ''
ourcompose_portal_rundeck_apitoken: ''
ourcompose_rundeck_apitoken: ''
ourcompose_portal_allow_cr: no
ourcompose_portal_admin_password: 'testpassword'
ourcompose_portal_org_name: "{{ ourcompose_common_domain.split('.')[0].upper() }}"
ourcompose_portal_admin_email: "{{ ourcompose_common_admin }}@{{ ourcompose_common_domain }}"
ourcompose_portal_initial_install: "0"
# range takes (i, j) where the generated ints are [i, i+1, i+2, ..., j-1].
# So, by doing this, we are actually NOT allowing anything to be set at 3:60, etc.
# but the highest option we could have would be 5:59
ourcompose_portal_cron_minute: "{{ range(0, 60) | random }}"
ourcompose_portal_cron_hour: "{{ range(3, 5) | random }}"
ourcompose_portal_cron_day: "*/2"
ourcompose_portal_cron_healthcheck: true
ourcompose_portal_cron_backup: false
ourcompose_portal_bind_mountpoints:
  - {location: '/portal/packs/', directory: '/app/public/packs'}
ourcompose_portal_mariadb_present: |
  CREATE USER IF NOT EXISTS 'portal'@'%' IDENTIFIED BY '{{ ourcompose_portal_backend_password }}';
  FLUSH privileges;
  CREATE DATABASE IF NOT EXISTS portal;
  GRANT ALL PRIVILEGES ON portal.* TO 'portal'@'%';
  FLUSH privileges;
ourcompose_portal_mariadb_absent: |
  DROP USER IF EXISTS 'portal'@'%';
  DROP DATABASE IF EXISTS portal;
ourcompose_portal_healthcheck: |
  wget --quiet --no-verbose --tries=1 --spider localhost:3000/portal \
  && wget --quiet --no-verbose --tries=1 --spider --no-check-certificate nginx$$(wget --quiet --no-verbose --tries=1 localhost:3000/portal -O - | grep -oe "[A-Za-z0-9/_-]\+.css" | head -n 1 | sed 's/^{{ ourcompose_common_domain.split(".")[-1] }}//') \
  || exit 1
