---
admin_email: "{{ environment_admin }}@{{ environment_domain }}"

do_oauth_token: "{{ vault_do_oauth_token }}"
do_droplet_size: 's-1vcpu-1gb'
do_droplet_image: 'ubuntu-18-04-x64'
do_block_storage_size: 10
do_object_name: "{{ environment_domain | replace('.', '-') }}--{{ ansible_date_time['date'] }}-{{ ansible_date_time['hour'] }}-{{ ansible_date_time['minute'] }}"

cloudns_api_user: 'ourcomposebot'
cloudns_api_pass: "{{ vault_cloudns_api_pass }}"

minio_server: 'https://backups.compositional.enterprises'
minio_access_key: 'ourcomposebot'
minio_secret_key: "{{ vault_minio_secret_key }}"

archive_backups_interval: 2

compositional_portal_production_yml_enc: 'ifGSMG2GXk0VB43u/4VtTRVr6XP3wWFXAytL6pfDFNPhOi+ysrHewlwMvZbUUgGA6LlQKfBMMihxJc3PnwJT+2dVADVu93pFVyvVOPziok5e3pE5N/Lweiw/NhQ9G8QIvSBdtc74232Ls2+U1wfq9e634yqdJCW03wNbgt4OEDaWG+tPqBHvHWJ84FlBke/sQLTIgRUNM5VqLDBNQVG6L8klNjzdeAtAQIw9/ZUMCKFvLiLdqBO1W9BeNu0lc6c1hXOgYb5J4b9WD+e/GauI68Huxu9XoMR5nHbwMZXJo+LEGkxFbjehQOUp8Xra64Z0lkZy1yR5YtZy2Lp1ASMuRCSUJN1PVstpCkI5NLLeawngkkZgbQDIp3wNuGs2jqmOtrFvMmMGAk+3+P2BNRKGUmuSh7RlVYIjm0jWWMYM20xzE4mawVFzYxkey+7GML7dDCGRwCfGxrxUcOA/BBGLVx6l9pR9xkk55zIQURXWrzbk16v7Al+fZi9JzsFLtQ5wkwTWZAKqtQoZNFxjKIrtDpCOG+eJ71RdSzSPEuJmnzKzqPZieIBFqTeLdMmX4IwKCVaAGuYG1EhYV9EcOQutSVYXHYGKEx89XwTnuma3OXt0r3UFqKQpyMd2N0Jdy7a01nakxot8mwzBxdDBd24/J2GJvGawnJNGBAMevJLRfo66jyxiITVcR0o3AUjLvLYNld6sM5LqQQDOK3wuT42NCnjLzX1WFwQ4By5jc9QbOsvSMflkwj8JodUfk4EeQR0/QqImigcEdU+vl59QSlhrNBrMz5wIMND5vTjX1AJdJYVAeG1o8k+GS5MvL9zXkSVS64+F6ydwg1jM96jl7TxW+5ugq6LTcOQs4LfAPfj1hEs33fVmSrhb66itU8kUQe/ncHwDsDnIL1wao7gxtj2IDqX5ifnfwQxw4aJWjKZlMx3PD7sEhMAG+evOw7C8lbn5/93fYWaJkcDVsJqI/h1uy6KQm0jZKAGAkng3J7Oyb6pU8y5h8Lo+fz3dIjIk1fGJSS5skiPpcWEFRAGzSnvPLhoFcQE2LesjCecpkAxx/yHl4ktSeqZgcrhIzSYeN2XlwZ8VPGo0SeU1tvEtyVXv6rn0+IGO0qqOa2VGTxNuD4a0gEeoRHIy7RsSFqHFkFJ4Vp26GqSGJFDaoXX2jJdQ08QCDab2cpmkpovhhhSwkAkzx38YkXmwVe7fV72Urr/3zbuMuiODcsjrCiNOp3/4boeW3QkshWFgUuzsnxawK5HLXy12ZxF0IYRg+fdO4mpBXh5BuxV4v32VUc2XezVijV3H6Doc/ffHNgdYUhn6j8knA3YC88NirfqIjXehDn3kik4aFmNf48BqbRqnIxLWBmb2HUsedvE1r+uJP961iVOCntXxPIIvYqSw6RbkNOI=--I2QdDawThO5kHvSk--p72dsnONr1WqSHw68sQtxA=='
compositional_portal_production_key: "{{ vault_compositional_portal_production_key }}"
ourcompose_ourcomposebot_ssh_key: "{{ vault_ourcompose_ourcomposebot_ssh_key }}"
compositional_portal_ourcomposebot_ro_key: "{{ vault_compositional_portal_ourcomposebot_ro_key }}"
