---
admin_email: "{{ environment_admin }}@{{ environment_domain }}"
do_oauth_token: "{{ vault_do_oauth_token }}"
do_droplet_size: 's-1vcpu-1gb'

cloudns_api_user: 'ourcomposebot'
cloudns_api_pass: "{{ vault_cloudns_api_pass }}"

minio_server: 'https://backups.compositional.enterprises'
minio_access_key: 'ourcomposebot'
minio_secret_key: "{{ vault_minio_secret_key }}"

archive_backups_interval: 2

compositional_portal_production_yml_enc: 'u0RLDShYfCUhmXv4MXJo1fq6t/zgZUJBVfXSIumtRHWcKeX3YbcnEXXy2Fm+/W/zri+eWuECyU+EExdNzECX7nZWEmAtKnYqpjucuAO3si/99DCerQBUuoM5G6osha3SpGdzkhumXB7aHeCRJdZuIk8NDOeYhtqedTP5Fr9DBTbSdqpgw71rscf3svSc++Jp+6XTTD7KeDh5UvtZ/64U18WILkZDfq1UAvqVUc1k6qGZsPFrylRl5PMW3G3aQB8vT2bR2bLFShp5cDlhoOkDcCDvI4sKOD8RKK0gXR0Rj9pofRbAF2xOU6ULSCXvxdiHf9eS9+6NivD6pp6Z5GR8Qmy/1w0hdW7qJ2Cl8ehzYMVccgncSh17YL6NLiGpi1dkI6Z5tlO+LzDg9k7JsTY/3kxDa3JskXwSRGXHQlktdC7NtkIrBZNYyeaCQQiH4TF/i+xJD4PNuEc8XdWrD42n1JK1rp+2u3MckCUz7iSM9RgOzdwUQSlNijeNgELMvXjF8zdeuhSZqJgN3wDyaEC424Y7CTu0AGQEXlaZBsR/N14pBysCrSucy4oZ7QrEfNgYQYfH5ni7Lz7a642UYX+C7aQZhPRkO+KSU4Utzw4AnnLtQAaN4l4PGsKJJfuiTW78D6hUjVA9/HKk0BkaprTXVCi43BoebNrjLBoN0hB41t3trPa9RvSIu6w+T+myWMNxBMgDzjs7cHhSe3e9mVePb+qznaMBUKAWWLE8H3QiGIPbaATTJkcCqeReoLryH8NbQ2GiAK7wpeR/5sxSyM1uwyN+TV/OPOOniy51ZkPoZmEKRQmv8bbv8rUP/Sjez3n1sTJqZt3AZn87JA7UYwCWzkNkqC5S9I51SP8Kx33xNdzSxWHeuJGN4Jri4F5bq/aqzyqfT3yXp9MjQBYmvOAYuknUZVDETA==--WFOQ5sgDEuiPQclD--BRlw4rKRWRv3YfbwG6dTKQ=='
compositional_portal_production_key: "{{ vault_compositional_portal_production_key }}"

