---
ourcompose_akaunting_state: 'running'
ourcompose_akaunting_version: '2.1'
ourcompose_akaunting_storage: 'local'
ourcompose_akaunting_backend_password: 'testpassword'
ourcompose_akaunting_admin_password: "testpassword"
ourcompose_akaunting_bind_mountpoints:
  - {location: '/akaunting/public/css/', directory: '/var/www/html/public/css'}
  - {location: '/akaunting/public/files/', directory: '/var/www/html/public/files'}
  - {location: '/akaunting/public/img/', directory: '/var/www/html/public/img'}
  - {location: '/akaunting/public/vendor/', directory: '/var/www/html/public/vendor'}
  - {location: '/akaunting/public/js/', directory: '/var/www/html/public/js'}
ourcompose_akaunting_mariadb_present: |
  CREATE USER IF NOT EXISTS 'akaunting'@'%' IDENTIFIED BY '{{ ourcompose_akaunting_backend_password }}';
  CREATE DATABASE IF NOT EXISTS akaunting;
  GRANT ALL PRIVILEGES ON akaunting.* TO 'akaunting'@'%' IDENTIFIED BY '{{ ourcompose_akaunting_backend_password }}';
ourcompose_akaunting_mariadb_absent: |
  DROP USER IF EXISTS 'akaunting'@'%';
  DROP DATABASE IF EXISTS akaunting;
ourcompose_akaunting_healthcheck: |
  curl localhost \
  && curl -sSL --insecure nginx/akaunting/$$(curl localhost | grep -oe 'public/css/[0-9a-zA-Z-]\+\.css' | head -n 1) \
  || exit 1
