---
- name: (absent) Stop the container before removing it
  include_tasks: stopped.yml

- name: (absent) The mariadb project is absented
  community.docker.docker_container:
    name: mariadb
    state: absent

- name: (absent) Remove the docker image
  community.docker.docker_image:
    name: mariadb
    state: absent
    force_absent: yes

- name: (absent) Remove the host bind mount volumes
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/srv/{{ ourcompose_mariadb_storage }}/mariadb_mysql"
    - "/srv/{{ ourcompose_mariadb_storage }}/mariadb_conf.d"
