---
ourcompose_rundeck_state: 'running'
ourcompose_dep_state: "{{ ourcompose_rundeck_state }}"
ourcompose_rundeck_version: '3.3.17'
ourcompose_rundeck_storage: 'local'
ourcompose_rundeck_admin_password: 'testpassword'
ourcompose_rundeck_backend_password: 'testpassword'
ourcompose_rundeck_api_tokens_duration_max: '0'
ourcompose_rundeck_bind_mountpoints:
  - {location: '/rundeck/assets/', directory: '/srv/{{ ourcompose_rundeck_storage }}/rundeck_etc/assets'}
ourcompose_rundeck_mariadb_present: |
  CREATE USER IF NOT EXISTS 'rundeck'@'%' IDENTIFIED BY '{{ ourcompose_rundeck_backend_password }}';
  FLUSH privileges;
  CREATE DATABASE IF NOT EXISTS rundeck;
  GRANT ALL PRIVILEGES ON rundeck.* TO 'rundeck'@'%';
  FLUSH privileges;
ourcompose_rundeck_mariadb_absent: |
  DROP USER IF EXISTS 'rundeck'@'%';
  DROP DATABASE IF EXISTS rundeck;
ourcompose_rundeck_additional_setup: |
  echo "Hello, World!"
  echo "Command number 2"
ourcompose_rundeck_healthcheck: |
  curl -sSL --fail localhost:4440/rundeck \
  && curl -sSL --fail --insecure nginx$$(curl -sSL --fail localhost:4440/rundeck | grep -oe '/rundeck/assets/static/css/components/theme-[a-f0-9]\+\.css') \
  || exit 1
