---
ourcompose_jekyll_state: 'running'
ourcompose_dep_state: "{{ ourcompose_jekyll_state }}"
# https://jekyllrb.com/news/releases/
ourcompose_jekyll_version: '4.2.2'
ourcompose_jekyll_storage: 'local'
ourcompose_jekyll_port: '8080'
ourcompose_jekyll_git_url: 'https://github.com/volny/creative-theme-jekyll.git'
ourcompose_jekyll_git_branch: 'master'
ourcompose_jekyll_bind_mountpoints:
  - {location: '/jekyll/', directory: '/srv/{{ ourcompose_jekyll_storage }}/jekyll_jekyll/_site'}
ourcompose_jekyll_extra_commands: |
  echo "Hello, World!"
  echo "Command number 2"
# With this healthcheck we are doing two things. The first thing is to check the root jekyll page.
# The second thing is a bit more involved. We are getting that page again, and checking for the first path
# to an image. Once we get the path to that image, we try to get that image to make sure that the reverse
# proxy is doing it's job buffering the assets correctly. However, we only do this in the case that the
# reverse proxy is, in fact, buffering anything. We do this by checking to make sure that there are
# some bind mountpoints that are being used, and then checking a file that falls into one of them.
# We lastly do some trickery to make sure that image is within any of the bind_mountpoints.
# We're also doing a substitution of the last part of the ourcompose_common_domain (e.g. ".com") and
# removing that, since there is the possibility of that part of the url getting caught if the full
# path to the resource is given in the link. We exclude periods though, so it's only the last part
# minus the period.
ourcompose_jekyll_healthcheck: |
  wget --quiet --no-verbose --tries=1 --spider localhost:8080/jekyll/ \
  {% if ourcompose_jekyll_bind_mountpoints | length > 0 %} \
    && set -o pipefail \
    && path=$$(wget --quiet --no-check-certificate localhost:8080/jekyll/ -O - |\
            grep -oe '[a-zA-Z0-9/_-]\+.png\|[a-zA-Z0-9/_-]\+.jpg\|[a-zA-Z0-9/_-]\+.jpeg' |\
            grep -v '^image/*' |\
            grep -e "{% for bind_mountpoint in ourcompose_jekyll_bind_mountpoints %}{{ bind_mountpoint['location'] }}\|{{ bind_mountpoint['location'].split('/')[2:] | join('/') }}{% if not loop.last %}\|{% endif %}{% endfor %}" |\
            sed 's/^{{ ourcompose_common_domain.split(".")[-1] }}//' |\
            head -n 1) \
    && prefix='/jekyll' \
    && path=$$(echo ${path} | sed 's#/jekyll##') \
    && prefix='/jekyll/' \
    && path=$$prefix$$path \
    && wget --quiet --no-verbose --tries=1 --spider --no-check-certificate nginx/$${path} \
  {% endif %} \
  || exit 1
ourcompose_jekyll_csp:
  default-src:
  - 'none'
  script-src:
  - 'self'
  connect-src:
  - 'self'
  img-src:
  - 'self'
  style-src:
  - 'self'
