---
- name: (bitcoind) The bitcoind data dir is created
  file:
    path: "/srv/{{ compositional_jekyll_storage }}/bitcoind_data/"
    state: directory
    recurse: True

- name: (bitcoind) Bitcoin.conf is templated
  template:
    src: ../templates/bitcoind_bitcoin.conf.j2
    dest: "/srv/{{ compositional_jekyll_storage }}/bitcoind_data/bitcoin.conf"

- name: (bitcoind) Determine whether the bitcoind service is existing yet
  shell:
    cmd: docker ps -a | tr -s ' ' | rev | cut -d ' ' -f 1 | rev | grep bitcoind
  failed_when: False
  register: compositional_bitcoind_existing

- name: (bitcoind) The latest bitcoind service is built and {{ compositional_bitcoind_state }}
  docker_compose:
    project_name: bitcoind
    definition:
      version: '3.6'
      services:
          bitcoind:
            image: "zquestz/bitcoin-unlimited:{{ compositional_bitcoind_version }}"
            container_name: 'bitcoind'
            volumes:
              - "/srv/{{ compositional_bitcoind_storage }}/bitcoind_data:/data"
            ports:
              - "8333:8333"
              # JSON-RPC
              - "8332:8332"
            healthcheck:
              test: "{{ compositional_bitcoind_healthcheck }}"
              interval: 5s
              timeout: 30s
              retries: 3
    pull: "{{ compositional_bitcoind_pull }}"
    state: "{{ compositional_bitcoind_state }}"
    # If the container is not already present, we don't want to pass
    # the 'restarted' parameter, we just want it restarted regularly.
    restarted: "{{ not compositional_bitcoind_existing['rc'] }}"
    timeout: 200
  register: compositional_bitcoind_output
