---
- name: Use python3 if we haven't already set a custom interpreter
  set_fact:
    ansible_python_interpreter: "/usr/bin/env python3"
  when: ansible_python_interpreter is not defined

- name: Ensure that the local and remote directories are configured
  file:
    path: "/srv/{{ item }}"
    recurse: yes
    state: directory
  loop:
    - 'local'
    - 'remote'

- name: Set up PATH environment in the crontab
  cron:
    name: PATH
    env: yes
    job: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'

- name: Set up default openssl certs
  when: compositional_nginx_cert_privkey == "/usr/local/share/certs/privkey.pem"
  block:
    - name: Create the certs directory
      file:
        path: "{{ compositional_nginx_cert_privkey | dirname }}"
        recurse: True
        state: directory

    - name: Create the cert files
      shell:
        cmd: openssl req -newkey rsa:2048 -new -x509 -days 3650 -passout 'pass:{{ compositional_nginx_cert_password }}' -subj '/CN={{ inventory_hostname }}' -keyout {{ compositional_nginx_cert_privkey }} -out {{ compositional_nginx_cert_fullchain }}
        creates: "{{ compositional_nginx_cert_privkey }}"
      register: compositional_main_create_cert_files

    - name: Unencrypt the keyfile
      shell:
        cmd: openssl rsa -passin 'pass:{{ compositional_nginx_cert_password }}' -in {{ compositional_nginx_cert_privkey }} -out {{ compositional_nginx_cert_privkey }}
      when: compositional_main_create_cert_files['changed']

- include_tasks: "./{{ item }}.yml"
  with_items:
    - "{{ compositional_frontend_service }}"
    - "{{ compositional_backend_service }}"

- include_tasks: "./portal.yml"
  when: "'portal' not in compositional_services"

- name: Setup Services
  block:
    - include_tasks: "./{{ item }}.yml"
      with_items: "{{ compositional_services }}"

    - name: Trigger any container restarts here
      meta: flush_handlers

    - include_tasks: "./bind_mountpoints.yml"
      when: compositional_proxy_bind_mountpoints | length > 0

  when: compositional_setup_services | bool
