---
dependencies:
  - compositionalenterprises.ourcompose.common
  - role: compositionalenterprises.ourcompose.nginx
    when: ourcompose_dep_state == 'running'
  - role: compositionalenterprises.ourcompose.portal
    ourcompose_portal_restarted: false
    when: ourcompose_dep_state == 'running'
