#
# This playbook sets up a Kanboard instance on either a single host or on a multi-tiered deployment.
#
#   ansible-playbook -i environment/hosts.yml playbooks/site.yml
#
---
- name: Roles in Common
  hosts: compositional
  become: yes
  vars_files:
    - '../vars/all.yml'
  vars:
    certbot_auto_renew_options: "--quiet --no-self-upgrade --pre-hook='docker stop nginx' --post-hook='docker start nginx'"
    certbot_admin_email: "{{ environment_admin }}@{{ environment_domain }}"
    certbot_create_if_missing: True
    certbot_install_from_source: True
    certbot_certs:
      - domains:
        - "{{ environment_domain }}"
    docker__pip_packages:
      - "docker"
      - "python-apt"
  roles:
    - { role: docker }
    - { role: certbot }
    - { role: compositional, tags: ['comp'], ansible_python_interpreter: "/usr/bin/env python-docker" }
