---
- import_playbook: 'minio_setup.yml'

- hosts: all
  vars_files:
    - ../environment/group_vars/all/all.yml
  tasks:
    - name: Install jq
      apt:
        name: jq
        state: latest
        update_cache: True
      register: pkg_install
      retries: 60
      delay: 5
      # Here we're also saying to retry on if we're facing a 'could not get lock'.
      # See: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#examples
      until: pkg_install is success or (
        not pkg_install['msg'] | d() | regex_search('Failed to lock apt|Could not get lock')

    - name: Get all of the bucket names
      shell: "/usr/local/bin/mc --json ls backups/ocbackups | jq '.key' | tr -d '\"' | grep {{ environment_domain | replace('.', '-') }}"
      register: archive_backups_domain_archives
      # We aren't going to have this fail since the very first time there will be no results to grep,
      # which would otherwise lead to a non-zero return code.
      failed_when: False

    - name: Delete any images that need deleting
      command: "mc rm backups/ocbackups/{{ item }}"
      loop: "{{ archive_backups_domain_archives['stdout_lines'] }}"
