---
- name: Get DO Droplet Info
  hosts: localhost
  connection: local
  vars_prompt:
    - name: oauth_token
      prompt: "Enter your OAUTH Token"
      private: True
  tasks:
    - name: Run get droplets info script
      script: ../bin/get_droplets_of_same_domain.py --token {{ oauth_token }}
      register: my_droplets

    - debug:
        var: item.split('$')[1]
      when: item.split('$')[0].startswith({{ environment_domain | replace('.', '-') }})
      with_items: "{{ my_droplets['stdout_lines'] }}"

    - name: delete digital_ocean_droplet
      digital_ocean_droplet:
        state: absent
        id: "{{ item.split('$')[1] }}"
        oauth_token: "{{ oauth_token }}"
      when: item.split('$')[0].startswith('ldap1')
      with_items: "{{ my_droplets['stdout_lines'] }}"
