- name: Fact Gathering
  hosts: localhost
  connection: local
  gather_facts: False
  pre_tasks:
    - name: Gather the values for all of the storage variables
      set_fact:
        storage_vars_list:  "{% for i in lookup('varnames', '^compositional_.+_storage', wantlist=True) %}{{ lookup('vars', i) }},{% endfor %}"

- name: Deploy Droplet
  import_playbook: create_droplet.yml

- name: Inventory Management
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Add newly-created droplet to new compositional host
      add_host:
        hostname: "{{ hostvars['localhost']['my_droplet']['data']['ip_address'] }}"
        groups:
          - 'new'
          - 'compositional'

- name: Establish Connection
  gather_facts: False
  hosts: compositional
  tasks:
    - name: Add Droplet to DNS while it finishes spinning up
       # Yes, these lines should end with trailing whitespace
      command: >
        ../bin/cloudns.py 
        --apiuser "{{ cloudns_api_user }}" 
        --apipass "{{ cloudns_api_pass }}" 
        --address "{{ hostvars['localhost']['new_floating_ip']['data']['floating_ip']['ip'] }}" 
        --fqdn "{{ environment_domain }}" 
        --type 'add'
      delegate_to: localhost

    - name: Establish an ssh connection
      wait_for_connection:

- name: Block Storage
  import_playbook: block_storage.yml
  when: "'remote' in hostvars['localhost']['storage_vars_list'].split(',')"

- name: Infrastructure Services
  import_playbook: services.yml

- name: Update the hosts file with the new droplet's address
  hosts: localhost
  connection: local
  gather_facts: True
  tasks:
    - name: Register realpath of hosts.yml file
      local_action:
        module: shell
        cmd: realpath ../environment/hosts.yml
      register: hosts_realpath

    - name: Replace the old server's IP with the new server's IP in the hosts.yml file
      local_action:
        module: shell
        cmd: ../bin/replace_host.py -i "{{ groups['new'][0] }}" -f "{{ hosts_realpath['stdout'].strip() }}"

    - name: Add the hosts.yml file with the new host present
      local_action:
        module: shell
        cmd: git --git-dir={{ '/'.join(hosts_realpath['stdout'].split('/')[:-1]) }}/.git add hosts.yml
        chdir: ../environment/

    - name: Commit the hosts.yml file with the new host present
      local_action:
        module: shell
        cmd: git --git-dir={{ '/'.join(hosts_realpath['stdout'].split('/')[:-1]) }}/.git commit -m "Updated to new inventory host {{ groups['new'][0] }} on {{ ansible_date_time['date'] }}-{{ ansible_date_time['hour'] }}-{{ ansible_date_time['minute'] }}" hosts.yml
        chdir: ../environment/

    - name: Push that latest commit
      local_action:
        module: shell
        cmd: git --git-dir={{ '/'.join(hosts_realpath['stdout'].split('/')[:-1]) }}/.git push
        chdir: ../environment/
