#
# This playbook sets up a Kanboard instance on either a single host or on a multi-tiered deployment.
#
#   ansible-playbook -i environment/hosts.yml playbooks/site.yml
#
---
- name: DO VM Setup
  hosts: localhost
  connection: local
  vars_files:
    - '../environment/group_vars/compositional/all.yml'
      #- '../environment/group_vars/compositional/vault.yml'
    - '../vars/all.yml'

  pre_tasks:
    - name: Prompt for oauth token
      block:
        - pause:
            prompt: "Enter your OAUTH Token"
            echo: no
          register: oauth_token_prompt

        - set_fact:
            oauth_token: oauth_token_prompt['user_input']
          no_log: True

      when: not hostvars['localhost']['oauth_token']

    - name: Get SSH key facts
      digital_ocean_sshkey_facts:
        oauth_token: "{{ oauth_token }}"
      register: ssh_key_facts

    - name: Set environment and date-formatted name for things
      set_fact:
        do_object_name: "{{ environment_domain | replace('.', '-') }}--{{ ansible_date_time['date'] }}-{{ ansible_date_time['hour'] }}-{{ ansible_date_time['minute'] }}"

  tasks:
    - name: create a new droplet
      digital_ocean_droplet:
        state: present
        name: "{{ do_object_name }}"
        size: 's-1vcpu-1gb'
        oauth_token: "{{ oauth_token }}"
        region: 'nyc3'
        image: 'ubuntu-16-04-x64'
        ssh_keys: "{{ ssh_key_facts['ansible_facts']['ssh_keys'] | map(attribute='id') | list }}"
        private_networking: True
        wait_timeout: 500
      register: my_droplet

