- name: Fact Gathering
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - '../environment/group_vars/compositional/all.yml'
    - '../environment/group_vars/compositional/vault.yml'
    - '../vars/all.yml'

  vars_prompt:
    - name: oauth_token
      prompt: "Enter your OAUTH Token"
      private: True

  pre_tasks:
    - name: Gather the values for all of the storage variables
      set_fact:
        storage_vars_list:  "{% for i in lookup('varnames', '^compositional_.+_storage', wantlist=True) %}{{ lookup('vars', i) }},{% endfor %}"

  tasks:
    - set_fact:
        oauth_token: "{{ oauth_token }}"
      no_log: True

- name: Deploy Droplet
  import_playbook: deploy_new_environment_domain_droplet.yml

- name: Inventory Management
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Add newly-created droplet to new compositional host
      add_host:
        name: "{{ hostvars['localhost']['my_droplet']['data']['ip_address'] }}"
        group: 'new'

- name: Establish Connection
  gather_facts: False
  hosts: new
  tasks:
    - name: Establish an ssh connection once the droplet is ready for it
      wait_for_connection:

- name: Block Storage
  import_playbook: ./deploy_new_block_storage_volume.yml
  when: "'remote' in hostvars['localhost']['storage_vars_list'].split(',')"

- name: Infrastructure Services
  import_playbook: all_env_services.yml
