---
- name: Install Skeleton
  hosts: all
  become: yes
  vars_files:
    - ../environment/group_vars/all/all.yml
  vars:
    docker__pip_packages:
      - "docker"
      - "python-apt"
    certbot_auto_renew_options: "--quiet --no-self-upgrade --pre-hook='docker stop proxy' --post-hook='docker start proxy'"
    certbot_admin_email: "{{ environment_admin }}@{{ environment_domain }}"
    certbot_create_if_missing: True
    certbot_install_from_source: False
    certbot_create_standalone_stop_services:
      - 'docker'
    certbot_certs:
      - domains: "{{ [environment_domain] + compositional_domain_redirects | default({}) | map(attribute='domain') | list }}"
  pre_tasks:
    - name: Keep trying to get the filelock until we can
      register: filelock
      shell: "with-lock-ex -f /var/lib/dpkg/lock-frontend sleep 1"
      until: filelock['rc'] == 0
      retries: 60
      delay: 5

    - name: Update all packages on the system
      apt:
        name: '*'
        state: latest
        update_cache: True

    #
    # TODO: LEGACY
    #
    - name: Determine presence of legacy python-docker
      stat:
        path: '/usr/local/bin/python-docker'
      register: install_services_python_docker

    - name: Link the python version for legacy clients
      file:
        src: '/usr/local/bin/python-docker'
        path: '/usr/local/bin/python3-docker'
        state: link
      when: install_services_python_docker['exists'] is defined

  roles:
    - role: swapfile
      swapfile_size: '4G'
    - role: docker
    - role: certbot
    - role: compositional
      tags: ['comp']
      ansible_python_interpreter: "/usr/bin/env python3-docker"
      # Here we're only installing the proxy and the database
      compositional_setup_services: False

  post_tasks:
    - name: Create podcast download-tracking script on ourcompose.com
      block:
        - name: Create episode_stats directory
          file:
            path: "/srv/local/nginx_episode_stats"
            state: directory

        - name: Place the script
          copy:
            src: ../files/episode_stats.sh
            dest: /root/episode_stats.sh
            mode: 0755

        - name: Add cronjob to run at the top of every hour
          cron:
            name: "Run the episode stats report"
            special_time: "hourly"
            job: /root/episode_stats.sh

      when: "'{{ environment_domain }}' == 'ourcompose.com'"
      tags: ['comp']
