---
- hosts: compositional
  tasks:
    - name: Backups directory exists
      file:
        path: '/srv/{{ compositional_mariadb_storage | default("local") }}/database_mysql/backups'
        state: 'directory'
        owner: '999'
        group: 'docker'
        mode: 0740

    - name: Perform mysqldump
      shell: "
        docker exec -it database bash -c '
          mysqldump -u root -p{{ compositional_database_root_password }}
            --all-databases
            --single-transaction
            --quick
            --lock-tables=false
            > /var/lib/mysql/backups/full-backup-\
              {{ ansible_date_time['date'] }}-\
              {{ ansible_date_time['hour'] }}-\
              {{ ansible_date_time['minute'] }}'
        "

    - name: Perform mariabackup
      shell: "docker exec -it database bash -c '{{ item }}'"
      loop:
        - 'mariabackup --backup --target-dir=/var/lib/mysql/backups --user=root --password={{ compositional_database_root_password }}'
        - 'mariabackup --prepare --target-dir=/var/lib/mysql/backups --user=root --password={{ compositional_database_root_password }}'
