- name: Migrate
  vars_files:
    - ../environment/group_vars/all/all.yml
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    delete_droplet_prompt: False

  pre_tasks:
    - name: Gather the values for all of the storage variables
      set_fact:
        storage_vars_list:  "{% for i in lookup('varnames', '^compositional_.+_storage', wantlist=True) %}{{ lookup('vars', i) }},{% endfor %}"
        delete_droplet: "{{ delete_droplet_prompt }}"

- import_playbook: 'backup_mariadb.yml'
- import_playbook: 'rotate_snapshots.yml'
- import_playbook: 'create_droplet.yml'

- name: Put droplet into groups
  hosts: localhost
  vars_files:
    - ../environment/group_vars/all/all.yml
  connection: local
  gather_facts: False
  tasks:
    - name: Add existing droplet to old group
      add_host:
        name: "{{ groups['compositional'][0] }}"
        groups:
          - 'old'

    - name: Add newly-created droplet to new and compositional groups
      add_host:
        name: "{{ hostvars['localhost']['my_droplet']['data']['ip_address'] }}"
        groups:
          - 'compositional'
          - 'new'

- name: Establish Connection
  vars_files:
    - ../environment/group_vars/all/all.yml
  gather_facts: False
  hosts: compositional
  tasks:
    - name: Establish an ssh connection
      wait_for_connection:

- import_playbook: 'create_block_storage.yml'
  when: "'remote' in hostvars['localhost']['storage_vars_list'].split(',')"

- import_playbook: 'transfer_data.yml'

- name: Install services before data restoration
  import_playbook: 'install_skeleton.yml'
  when: inventory_hostname in groups['new']

- name: Restore the database backups
  import_playbook: 'restore_mariadb.yml'

- name: Install services after data restoration
  import_playbook: 'install_services.yml'
  when: inventory_hostname in groups['new']

- import_playbook: 'transfer_ip.yml'

- import_playbook: 'delete_droplet.yml'
  when: delete_droplet | bool

- name: Update the hosts file with the new droplet's address
  vars_files:
    - ../environment/group_vars/all/all.yml
  hosts: localhost
  connection: local
  gather_facts: True
  tasks:
    - name: Register realpath of hosts.yml file
      local_action:
        module: shell
        cmd: realpath ../environment/hosts.yml
      register: hosts_realpath

    - name: Replace the old server's IP with the new server's IP in the hosts.yml file
      local_action:
        module: shell
        cmd: ../bin/replace_host.py -i "{{ groups['new'][0] }}" -f "{{ hosts_realpath['stdout'].strip() }}"

    - name: Add the hosts.yml file with the new host present
      local_action:
        module: shell
        cmd: git --git-dir={{ '/'.join(hosts_realpath['stdout'].split('/')[:-1]) }}/.git add hosts.yml
        chdir: ../environment/

    - name: Commit the hosts.yml file with the new host present
      local_action:
        module: shell
        cmd: git --git-dir={{ '/'.join(hosts_realpath['stdout'].split('/')[:-1]) }}/.git commit -m "Updated to new inventory host {{ groups['new'][0] }} on {{ ansible_date_time['date'] }}-{{ ansible_date_time['hour'] }}-{{ ansible_date_time['minute'] }}" hosts.yml
        chdir: ../environment/

    - name: Push that latest commit
      local_action:
        module: shell
        cmd: git --git-dir={{ '/'.join(hosts_realpath['stdout'].split('/')[:-1]) }}/.git push
        chdir: ../environment/
