- name: Migrate
  hosts: localhost
  connection: local
  gather_facts: False
  pre_tasks:
    - name: Gather the values for all of the storage variables
      set_fact:
        storage_vars_list:  "{% for i in lookup('varnames', '^compositional_.+_storage', wantlist=True) %}{{ lookup('vars', i) }},{% endfor %}"

- import_playbook: 'create_droplet.yml'

- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Add newly-created droplet to new compositional host
      add_host:
        name: "{{ hostvars['localhost']['my_droplet']['data']['ip_address'] }}"
        group: 'new'

- import_playbook: 'block_storage.yml'
  when: "'remote' in hostvars['localhost']['storage_vars_list'].split(',')"

- import_playbook: 'transfer_data.yml'

- import_playbook: 'services.yml'
  when: inventory_hostname in groups['new']

- import_playbook: 'transfer_data.yml'
- import_playbook: 'transfer_ip.yml'
- import_playbook: 'delete_droplet.yml'

- name: Update the hosts file with the new droplet's address
  hosts: localhost
  connection: local
  gather_facts: True
  tasks:
    - name: Register realpath of hosts.yml file
      local_action:
        module: shell
        cmd: realpath ../environment/hosts.yml
      register: hosts_realpath

    - name: Replace the old server's IP with the new server's IP in the hosts.yml file
      local_action:
        module: shell
        cmd: ../bin/replace_host.py -i "{{ inventory_hostname }}" -f "{{ hosts_realpath['stdout'].strip() }}"

    - name: Add the hosts.yml file with the new host present
      local_action:
        module: shell
        cmd: git --git-dir={{ '/'.join(hosts_realpath['stdout'].split('/')[:-1]) }}/.git add hosts.yml
        chdir: ../environment/

    - name: Commit the hosts.yml file with the new host present
      local_action:
        module: shell
        cmd: git --git-dir={{ '/'.join(hosts_realpath['stdout'].split('/')[:-1]) }}/.git commit -m "Updated to new inventory host {{ inventory_hostname }} on {{ ansible_date_time['date'] }}-{{ ansible_date_time['hour'] }}-{{ ansible_date_time['minute'] }}" hosts.yml
        chdir: ../environment/

    - name: Push that latest commit
      local_action:
        module: shell
        cmd: git --git-dir={{ '/'.join(hosts_realpath['stdout'].split('/')[:-1]) }}/.git push
        chdir: ../environment/
