---
- name: Copy application data from one server to another
  hosts: all
  gather_facts: False
  tasks:
    - name: Generate SSH keys on compositional server
      block:
        - name: Generate ssh keypair
          shell: ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -q -N ""
          args:
            creates: /root/.ssh/id_ed25519

        - name: Get content of public key file
          shell: cat /root/.ssh/id_ed25519.pub
          register: compositional_root_public_key

      when: "'compositional' in group_names"

    - name: Setup new server to receive data
      block:
        - name: Make sure directories' parent directories are present
          file:
            path: "{{ item }}"
            state: directory
            recurse: yes
          loop:
            - '/var/lib/docker/volumes'
            - '/srv'

        - name: Add public key of root on compositional server to root on new server
          authorized_key:
            user: root
            state: present
            key: "{{ hostvars[groups['compositional'][0]]['compositional_root_public_key']['stdout'] }}"

      when: "'new' in group_names"

    - name: Finish Sync on compositional server
      block:
        - name: rsync directories over
          shell: rsync -ave "ssh -i /root/.ssh/id_ed25519 -o StrictHostKeyChecking=no" {{ item.src }} root@{{ groups['new'][0] }}:{{ item.dest }}
          loop:
            - {'src': '/etc/letsencrypt/', 'dest': '/etc/letsencrypt'}
            - {'src': '/var/lib/docker/volumes/*_*', 'dest': '/var/lib/docker/volumes'}
            - {'src': '/srv/', 'dest': '/srv'}

        - name: Remove SSH keypair for root on compositional server
          file:
            path: "/root/.ssh/id_ed25519{{ item }}"
            state: absent
          loop:
            - '.pub'
            - ''

      when: "'compositional' in group_names"

    - name: Remove public key of root on compositional server for root on new server
      authorized_key:
        user: root
        state: absent
        key: "{{ hostvars[groups['compositional'][0]]['compositional_root_public_key']['stdout'] }}"
      when: "'new' in group_names"

